"""empty message

Revision ID: 2fb1178a7835
Revises: 4993a6ec775f
Create Date: 2017-04-29 17:03:51.507658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb1178a7835'
down_revision = '4993a6ec775f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'description')
    # ### end Alembic commands ###
