"""empty message

Revision ID: 8a0cd03b50d5
Revises: 2fb1178a7835
Create Date: 2017-04-29 21:30:22.299545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0cd03b50d5'
down_revision = '2fb1178a7835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
