"""empty message

Revision ID: abd8afb97cb7
Revises: 8a0cd03b50d5
Create Date: 2017-04-29 21:30:39.526816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd8afb97cb7'
down_revision = '8a0cd03b50d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'url')
    # ### end Alembic commands ###
